version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: |
      bash -c 'bash -s <<EOF
      if [ ! -f run.sh ]
      then
        git clone git@github.com:othernet-local/Litelist.git
        cd Litelist
        git fetch
        git checkout circle
        chmod +x run.sh
      fi
      ./run.sh
      EOF'
