version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: |
      bash -c 'bash -s <<EOF
      if [ ! -f run.sh ]
      then
        curl -o "run.sh" "https://github.com/othernet-local/Litelist/blob/circle/run.sh"
      fi
      chmod +x run.sh
      ./run.sh
      EOF'
