version: "3.6"

services:
  postgres:
    image: "postgres:11.0-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  web:
    build: "."
    depends_on:
      - "postgres"
    ports:
      - "4001:4001"
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
      - "static:/app/priv/static"
    command: "./run.sh"

volumes:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
