version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: ["docker cp run.sh app:/run.sh", "chmod +x run.sh", "./run.sh"]