version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: ["chmod +x run.sh", "docker cp /app:run.sh run.sh", "./run.sh"]