# Elixir CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: docker-compose build
      - run: docker-compose up
      - run: docker-compose run web mix test